In [1]:
import neuralnet as nn
import matplotlib.pyplot as plt
import numpy as np
import pickle
import time
from typing import List, Any
np.random.seed(123)

In [2]:
pool = nn.MaxPool2D()
unpool = nn.MaxUnPool2D(pool)

In [3]:
data = np.array([
    [1, 2, 1, 0,-1, 0, 7, 0],
    [1, 1,-1, 1,-1, 5,-3, 9],
    [0, 0, 3, 2, 1, 1, 8, 0],
    [0, 0, 1, 0, 1,-1, 0, 0],
    [1, 2, 1, 0, 7, 7, 4,-1],
    [1, 3, 1, 0, 1, 9,-9, 0],
    [1, 2, 1, 0, 7, 7, 4,-1],
    [1, 1,-1, 1,-1, 5,-3, 9],
]).reshape((8,8,1))
pooled = np.array([
    [3, 9],
    [3, 9]
]).reshape((2,2,1))
unpooled = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 9],
    [0, 0, 3, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 3, 0, 0, 0, 9, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
]).reshape((8,8,1))

In [4]:
np.round(data[:,:,0])

array([[ 1,  2,  1,  0, -1,  0,  7,  0],
       [ 1,  1, -1,  1, -1,  5, -3,  9],
       [ 0,  0,  3,  2,  1,  1,  8,  0],
       [ 0,  0,  1,  0,  1, -1,  0,  0],
       [ 1,  2,  1,  0,  7,  7,  4, -1],
       [ 1,  3,  1,  0,  1,  9, -9,  0],
       [ 1,  2,  1,  0,  7,  7,  4, -1],
       [ 1,  1, -1,  1, -1,  5, -3,  9]])

In [5]:
np.round(pooled[:,:,0])

array([[3, 9],
       [3, 9]])

In [6]:
np.round(unpooled[:,:,0])

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 9, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
out = pool.forward(np.concatenate((data,data),axis=2))
np.round(out[:,:,0] - pooled[:,:,0])

array([[0., 0.],
       [0., 0.]])

In [8]:
out2 = unpool.forward(out)
np.round(out2[:,:,0] - unpooled[:,:,0])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -9.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  9.]])